name: ExtraChillDesktop
options:
  bundleIdPrefix: com.extrachill
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
  groupSortPosition: top

targets:
  ExtraChillDesktop:
    type: application
    platform: macOS
    sources:
      - path: ExtraChillDesktop
        excludes:
          - Resources/Scripts/**
      - path: ExtraChillDesktop/Resources/Scripts
        buildPhase: resources
      - path: ExtraChillDesktop/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.extrachill.desktop
        PRODUCT_NAME: Extra Chill Desktop
        MARKETING_VERSION: 0.1.0
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.developer-tools
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2026 Extra Chill. All rights reserved."
        INFOPLIST_KEY_CFBundleDisplayName: "Extra Chill Desktop"
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
