name: Homeboy
options:
  bundleIdPrefix: com.extrachill
  deploymentTarget:
    macOS: "14.4"
  createIntermediateGroups: true
  groupSortPosition: top

targets:
  Homeboy:
    type: application
    platform: macOS
    sources:
      - path: Homeboy
        excludes:
          - Resources/Scripts/**
      - path: Homeboy/Resources/Scripts
        buildPhase: resources
      - path: Homeboy/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.extrachill.homeboy
        PRODUCT_NAME: Homeboy
        MARKETING_VERSION: 0.11.1
        CURRENT_PROJECT_VERSION: 12
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.developer-tools
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2026 Extra Chill. All rights reserved."
        INFOPLIST_KEY_CFBundleDisplayName: "Homeboy"
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.4"
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
